import { Project } from './types';

export const INITIAL_PROJECTS: Project[] = [
  // ================= SHORT FORM =================
  // Subcategory: Creators / Influencers
  {
    id: 'sf-creators-01',
    title: 'Social World — Brand Building',
    slug: 'social-world-brand-building',
    category: 'short_form',
    subcategory: 'creators_influencers',
    description: 'Dynamic brand-building vertical reel for creators with hook pacing, animated kinetic captions, and sound design.',
    thumbnail_url: '',
    video_url: '/videos/social world-brand building.mp4',
    client_name: 'Social World',
    role: 'Short-Form Video Editor',
    software: ['Adobe Premiere Pro', 'Adobe After Effects'],
    featured: true,
    display_order: 1,
    published: true,
    aspect_ratio: '9:16',
    duration: '00:39',
  },
  {
    id: 'sf-creators-02',
    title: 'XExamination — Podcast Reel',
    slug: 'xexamination-podcast-reel',
    category: 'short_form',
    subcategory: 'creators_influencers',
    description: 'High-retention podcast highlight short featuring camera punch-ins, synchronized typography, and impactful audio accents.',
    thumbnail_url: '',
    video_url: '/videos/XExamination-podcast reel.mp4',
    client_name: 'XExamination',
    role: 'Podcast Short-Form Editor',
    software: ['Adobe Premiere Pro', 'Adobe After Effects'],
    featured: true,
    display_order: 2,
    published: true,
    aspect_ratio: '9:16',
    duration: '01:02',
  },

  // Subcategory: Ad Reels
  {
    id: 'sf-ad-01',
    title: 'Mamu Show — Promo',
    slug: 'mamu-show-promo',
    category: 'short_form',
    subcategory: 'ad_reels',
    description: 'Fast-paced promotional ad reel cut to music rhythm, featuring kinetic motion elements and commercial hook pacing.',
    thumbnail_url: '',
    video_url: '/videos/mamu show-promo.mp4',
    client_name: 'Mamu Show',
    role: 'Promotional Ad Editor',
    software: ['Adobe Premiere Pro', 'Adobe After Effects'],
    featured: true,
    display_order: 3,
    published: true,
    aspect_ratio: '9:16',
    duration: '00:45',
  },
  {
    id: 'sf-ad-02',
    title: 'Simco — Paai',
    slug: 'simco-paai',
    category: 'short_form',
    subcategory: 'ad_reels',
    description: 'Commercial advertisement reel with macro product transitions, sound design, and clean visual storytelling.',
    thumbnail_url: '',
    video_url: '/videos/simco-paai.mp4',
    client_name: 'Simco',
    role: 'Commercial Video Editor',
    software: ['Adobe Premiere Pro', 'Adobe After Effects'],
    featured: true,
    display_order: 4,
    published: true,
    aspect_ratio: '9:16',
    duration: '00:50',
  },

  // Subcategory: Brand Promotion
  {
    id: 'sf-brand-01',
    title: 'Planet Life — Family Trip',
    slug: 'planet-life-family-trip',
    category: 'short_form',
    subcategory: 'brand_promotion',
    description: 'Cinematic brand travel edit featuring emotive lifestyle storytelling, rich color grading, and organic transitions.',
    thumbnail_url: '',
    video_url: '/videos/planet life-family trip.mp4',
    client_name: 'Planet Life',
    role: 'Brand Editor & Colorist',
    software: ['Adobe Premiere Pro', 'Adobe After Effects'],
    featured: true,
    display_order: 5,
    published: true,
    aspect_ratio: '9:16',
    duration: '00:38',
  },
  {
    id: 'sf-brand-02',
    title: 'Javelin Tiger — Water Usage',
    slug: 'javelin-tiger-water-usage',
    category: 'short_form',
    subcategory: 'brand_promotion',
    description: 'Brand awareness video blending kinetic motion graphics, crisp cut timing, and narrative pacing.',
    thumbnail_url: '',
    video_url: '/videos/javelin tiger-water usage.mp4',
    client_name: 'Javelin Tiger',
    role: 'Motion Designer & Editor',
    software: ['Adobe Premiere Pro', 'Adobe After Effects'],
    featured: true,
    display_order: 6,
    published: true,
    aspect_ratio: '9:16',
    duration: '00:53',
  },
  {
    id: 'sf-brand-03',
    title: 'Akitara — Hair Serum',
    slug: 'akitara-hair-serum',
    category: 'short_form',
    subcategory: 'brand_promotion',
    description: 'Aesthetic beauty commercial featuring macro product texture shots, benefit highlights, and elegant sound design.',
    thumbnail_url: '',
    video_url: '/videos/akitara-hair serum.mp4',
    client_name: 'Akitara',
    role: 'Commercial Brand Editor',
    software: ['Adobe Premiere Pro', 'Adobe After Effects'],
    featured: true,
    display_order: 7,
    published: true,
    aspect_ratio: '9:16',
    duration: '01:19',
  },

  // ================= LONG FORM =================
  // Subcategory: Podcasts
  {
    id: 'lf-podcast-01',
    title: 'XExamination — Podcast',
    slug: 'xexamination-podcast',
    category: 'long_form',
    subcategory: 'podcasts',
    description: 'Full studio podcast episode with multicam switching, dialogue cleanup, sound mastering, and lower-third graphics.',
    thumbnail_url: '',
    video_url: '/videos/XExamination-podcast.mp4',
    client_name: 'XExamination',
    role: 'Lead Podcast Editor & Sound Designer',
    software: ['Adobe Premiere Pro', 'Adobe Audition', 'Adobe After Effects'],
    featured: true,
    display_order: 8,
    published: true,
    aspect_ratio: '16:9',
    duration: '00:40',
  },

  // Subcategory: Advertisements
  {
    id: 'lf-ad-01',
    title: 'IQ Bizz Growth — Cafe Business School',
    slug: 'iq-bizz-growth-cafe-business-schl',
    category: 'long_form',
    subcategory: 'advertisements',
    description: 'Comprehensive business school commercial featuring on-site documentary b-roll, entrepreneur interviews, and branded motion graphics.',
    thumbnail_url: '',
    video_url: '/videos/IQ Bizz growth -cafe business schl.mp4',
    client_name: 'IQ Bizz Growth',
    role: 'Documentary & Commercial Editor',
    software: ['Adobe Premiere Pro', 'Adobe After Effects'],
    featured: true,
    display_order: 9,
    published: true,
    aspect_ratio: '16:9',
    duration: '02:51',
  },
];
